#!/data/data/com.termux/files/usr/bin/bash

# ==========================================
# Rahman CLI Main Loader
# ==========================================

BASE="$HOME/RahmanCLI"


# Load Alias System

if [ -f "$BASE/lib/alias.sh" ]; then
    source "$BASE/lib/alias.sh"
fi


# Load Theme

if [ -f "$BASE/lib/theme.sh" ]; then
    source "$BASE/lib/theme.sh"
    color
fi


COMMAND="$1"
shift


# Default Command

if [ -z "$COMMAND" ]; then
    COMMAND="help"
fi


# Apply Alias

if command -v load_alias >/dev/null 2>&1
then
    COMMAND=$(load_alias "$COMMAND")
fi



# Command Loader

COMMAND_FILE="$BASE/commands/$COMMAND.sh"


if [ -f "$COMMAND_FILE" ]; then

    bash "$COMMAND_FILE" "$@"

    reset_color

    exit 0

fi



# Plugin Loader

PLUGIN_FILE="$BASE/plugins/$COMMAND.sh"


if [ -f "$PLUGIN_FILE" ]; then

    bash "$PLUGIN_FILE" "$@"

    reset_color

    exit 0

fi



# Command Not Found

echo "================================"
echo "🚀 Rahman CLI"
echo "================================"

echo "Unknown command: $COMMAND"

echo ""

echo "Run:"
echo "  rahman help"

echo "================================"


reset_color

exit 1
