#!/data/data/com.termux/files/usr/bin/bash

BASE="$HOME/RahmanCLI"

COMMAND="$1"
shift

# No command
if [ -z "$COMMAND" ]; then
    COMMAND="help"
fi

# Command directory
COMMAND_SCRIPT="$BASE/commands/$COMMAND.sh"

# Plugin directory
PLUGIN_SCRIPT="$BASE/plugins/$COMMAND.sh"

# Execute command
if [ -f "$COMMAND_SCRIPT" ]; then
    bash "$COMMAND_SCRIPT" "$@"
    exit 0
fi

# Execute plugin
if [ -f "$PLUGIN_SCRIPT" ]; then
    bash "$PLUGIN_SCRIPT" "$@"
    exit 0
fi

echo "Unknown command: $COMMAND"
echo ""
echo "Run: rahman help"

exit 1
