weather=https://github.com/rahman2008-svg/RahmanCLI-Extensions/weather
flutter=https://github.com/rahman2008-svg/RahmanCLI-Extensions/flutter
firebase=https://github.com/rahman2008-svg/RahmanCLI-Extensions/firebase
