[TEMPLATES]

flask-api=https://github.com/rahman2008-svg/RahmanCLI-Templates/flask-api
fastapi-api=https://github.com/rahman2008-svg/RahmanCLI-Templates/fastapi-api
react-app=https://github.com/rahman2008-svg/RahmanCLI-Templates/react-app


[PLUGINS]

docker=https://github.com/rahman2008-svg/RahmanCLI-Plugins/docker
flutter=https://github.com/rahman2008-svg/RahmanCLI-Plugins/flutter
firebase=https://github.com/rahman2008-svg/RahmanCLI-Plugins/firebase
